import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'
import "./globals.css";
import { Providers } from "@/providers";
import { Header } from "@/widgets/Header";
import { AppSidebar } from "@/widgets/Sidebar";
import { MapProvider } from "@/context/MapContext";

export const metadata: Metadata = {
  title: "Decedrone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable} `}>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        <Providers>
          <AppSidebar />
          <main className="min-h-screen flex w-full gap-4 flex-col">
            <Header />
            <MapProvider>
              {children}
            </MapProvider>
          </main>
            
        </Providers>
      </body>
    </html>
  );
}
