"""add geometry column to hex_grid_cells

Revision ID: 147cacf5f564
Revises: 8480bc9116d3
Create Date: 2025-05-24 23:20:43.728657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '147cacf5f564'
down_revision = '8480bc9116d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drones', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('flight_requests', 'pilot_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('hex_grid_cells', sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('hex_grid_cells', 'geometry')
    op.alter_column('flight_requests', 'pilot_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('drones', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ### 